apiVersion: v1
kind: Service
metadata:
    name: "sspeiche-4828"
    labels:
        app: "sspeiche-4828"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "sspeiche-4828"